name: 测试go+mysql项目能不能运行

on:
  push:
    branches: [main]

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 设置MySql
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"  # 指定 MySQL 版本
          root-password: "123456"  # 设置 root 用户密码
          user: "root"  # 创建新用户
          password: "123456"  # 新用户的密码

      - name: 测试MySql连接
        run: |
          mysql -uroot -p123456 -e 'create database prod;'
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # - name: 构建
      #   run: go build -v ./...
      
      - name: 运行
        run: go mod tidy && go run ./cmd/*


# name: Go CI/CD(ai生成的)

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: '1.20'

#       - name: Cache Go Modules
#         uses: actions/cache@v3
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#           restore-keys: |
#             ${{ runner.os }}-go-

#       - name: Build
#         run: go build -v ./...
      
#       - name: 运行
#         run: go mod tidy && go run ./cmd/*

#       - name: Test
#         run: go test -v ./...